package cn.edu.xmu.oomall.order.mapper.generator;

import cn.edu.xmu.oomall.order.mapper.generator.po.OrderItemPo;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPaymentPo;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPaymentPoExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.data.jpa.repository.JpaRepository;

import javax.annotation.ManagedBean;

@Mapper
public interface OrderPaymentPoMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @DeleteProvider(type=OrderPaymentPoSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @Delete({
        "delete from order_payment",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @Insert({
        "insert into order_payment (`order_id`, `payment_id`, ",
        "`creator_id`, `creator_name`, ",
        "`modifier_id`, `modifier_name`, ",
        "`gmt_create`, `gmt_modified`)",
        "values (#{orderId,jdbcType=BIGINT}, #{paymentId,jdbcType=BIGINT}, ",
        "#{creatorId,jdbcType=BIGINT}, #{creatorName,jdbcType=VARCHAR}, ",
        "#{modifierId,jdbcType=BIGINT}, #{modifierName,jdbcType=VARCHAR}, ",
        "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrderPaymentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @InsertProvider(type=OrderPaymentPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(OrderPaymentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @SelectProvider(type=OrderPaymentPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OrderPaymentPo> selectByExample(OrderPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "`id`, `order_id`, `payment_id`, `creator_id`, `creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, `gmt_modified`",
        "from order_payment",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT),
        @Result(column="payment_id", property="paymentId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP)
    })
    OrderPaymentPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OrderPaymentPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") OrderPaymentPo row, @Param("example") OrderPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OrderPaymentPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") OrderPaymentPo row, @Param("example") OrderPaymentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @UpdateProvider(type=OrderPaymentPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderPaymentPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment
     *
     * @mbg.generated
     */
    @Update({
        "update order_payment",
        "set `order_id` = #{orderId,jdbcType=BIGINT},",
          "`payment_id` = #{paymentId,jdbcType=BIGINT},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderPaymentPo row);
}