package cn.edu.xmu.oomall.order.mapper.generator;

import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPo;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPoExample.Criteria;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPoExample.Criterion;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderPoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OrderPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String deleteByExample(OrderPoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("order_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String insertSelective(OrderPo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_order");
        
        if (row.getCustomerId() != null) {
            sql.VALUES("`customer_id`", "#{customerId,jdbcType=BIGINT}");
        }
        
        if (row.getShopId() != null) {
            sql.VALUES("`shop_id`", "#{shopId,jdbcType=BIGINT}");
        }
        
        if (row.getOrderSn() != null) {
            sql.VALUES("`order_sn`", "#{orderSn,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.VALUES("`pid`", "#{pid,jdbcType=BIGINT}");
        }
        
        if (row.getConsignee() != null) {
            sql.VALUES("`consignee`", "#{consignee,jdbcType=VARCHAR}");
        }
        
        if (row.getRegionId() != null) {
            sql.VALUES("`region_id`", "#{regionId,jdbcType=BIGINT}");
        }
        
        if (row.getAddress() != null) {
            sql.VALUES("`address`", "#{address,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.VALUES("`mobile`", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getMessage() != null) {
            sql.VALUES("`message`", "#{message,jdbcType=VARCHAR}");
        }
        
        if (row.getPackageId() != null) {
            sql.VALUES("`package_id`", "#{packageId,jdbcType=BIGINT}");
        }
        
        if (row.getExpressFee() != null) {
            sql.VALUES("`express_fee`", "#{expressFee,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.VALUES("`discount_price`", "#{discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getOriginPrice() != null) {
            sql.VALUES("`origin_price`", "#{originPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.VALUES("`point`", "#{point,jdbcType=BIGINT}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("`status`", "#{status,jdbcType=INTEGER}");
        }
        
        if (row.getCreatorId() != null) {
            sql.VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String selectByExample(OrderPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`customer_id`");
        sql.SELECT("`shop_id`");
        sql.SELECT("`order_sn`");
        sql.SELECT("`pid`");
        sql.SELECT("`consignee`");
        sql.SELECT("`region_id`");
        sql.SELECT("`address`");
        sql.SELECT("`mobile`");
        sql.SELECT("`message`");
        sql.SELECT("`package_id`");
        sql.SELECT("`express_fee`");
        sql.SELECT("`discount_price`");
        sql.SELECT("`origin_price`");
        sql.SELECT("`point`");
        sql.SELECT("`status`");
        sql.SELECT("`creator_id`");
        sql.SELECT("`creator_name`");
        sql.SELECT("`modifier_id`");
        sql.SELECT("`modifier_name`");
        sql.SELECT("`gmt_create`");
        sql.SELECT("`gmt_modified`");
        sql.FROM("order_order");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrderPo row = (OrderPo) parameter.get("row");
        OrderPoExample example = (OrderPoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("order_order");
        
        if (row.getId() != null) {
            sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getCustomerId() != null) {
            sql.SET("`customer_id` = #{row.customerId,jdbcType=BIGINT}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("`shop_id` = #{row.shopId,jdbcType=BIGINT}");
        }
        
        if (row.getOrderSn() != null) {
            sql.SET("`order_sn` = #{row.orderSn,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.SET("`pid` = #{row.pid,jdbcType=BIGINT}");
        }
        
        if (row.getConsignee() != null) {
            sql.SET("`consignee` = #{row.consignee,jdbcType=VARCHAR}");
        }
        
        if (row.getRegionId() != null) {
            sql.SET("`region_id` = #{row.regionId,jdbcType=BIGINT}");
        }
        
        if (row.getAddress() != null) {
            sql.SET("`address` = #{row.address,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.SET("`mobile` = #{row.mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getMessage() != null) {
            sql.SET("`message` = #{row.message,jdbcType=VARCHAR}");
        }
        
        if (row.getPackageId() != null) {
            sql.SET("`package_id` = #{row.packageId,jdbcType=BIGINT}");
        }
        
        if (row.getExpressFee() != null) {
            sql.SET("`express_fee` = #{row.expressFee,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{row.discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getOriginPrice() != null) {
            sql.SET("`origin_price` = #{row.originPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.SET("`point` = #{row.point,jdbcType=BIGINT}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{row.status,jdbcType=INTEGER}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("order_order");
        
        sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        sql.SET("`customer_id` = #{row.customerId,jdbcType=BIGINT}");
        sql.SET("`shop_id` = #{row.shopId,jdbcType=BIGINT}");
        sql.SET("`order_sn` = #{row.orderSn,jdbcType=VARCHAR}");
        sql.SET("`pid` = #{row.pid,jdbcType=BIGINT}");
        sql.SET("`consignee` = #{row.consignee,jdbcType=VARCHAR}");
        sql.SET("`region_id` = #{row.regionId,jdbcType=BIGINT}");
        sql.SET("`address` = #{row.address,jdbcType=VARCHAR}");
        sql.SET("`mobile` = #{row.mobile,jdbcType=VARCHAR}");
        sql.SET("`message` = #{row.message,jdbcType=VARCHAR}");
        sql.SET("`package_id` = #{row.packageId,jdbcType=BIGINT}");
        sql.SET("`express_fee` = #{row.expressFee,jdbcType=BIGINT}");
        sql.SET("`discount_price` = #{row.discountPrice,jdbcType=BIGINT}");
        sql.SET("`origin_price` = #{row.originPrice,jdbcType=BIGINT}");
        sql.SET("`point` = #{row.point,jdbcType=BIGINT}");
        sql.SET("`status` = #{row.status,jdbcType=INTEGER}");
        sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        
        OrderPoExample example = (OrderPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(OrderPo row) {
        SQL sql = new SQL();
        sql.UPDATE("order_order");
        
        if (row.getCustomerId() != null) {
            sql.SET("`customer_id` = #{customerId,jdbcType=BIGINT}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("`shop_id` = #{shopId,jdbcType=BIGINT}");
        }
        
        if (row.getOrderSn() != null) {
            sql.SET("`order_sn` = #{orderSn,jdbcType=VARCHAR}");
        }
        
        if (row.getPid() != null) {
            sql.SET("`pid` = #{pid,jdbcType=BIGINT}");
        }
        
        if (row.getConsignee() != null) {
            sql.SET("`consignee` = #{consignee,jdbcType=VARCHAR}");
        }
        
        if (row.getRegionId() != null) {
            sql.SET("`region_id` = #{regionId,jdbcType=BIGINT}");
        }
        
        if (row.getAddress() != null) {
            sql.SET("`address` = #{address,jdbcType=VARCHAR}");
        }
        
        if (row.getMobile() != null) {
            sql.SET("`mobile` = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (row.getMessage() != null) {
            sql.SET("`message` = #{message,jdbcType=VARCHAR}");
        }
        
        if (row.getPackageId() != null) {
            sql.SET("`package_id` = #{packageId,jdbcType=BIGINT}");
        }
        
        if (row.getExpressFee() != null) {
            sql.SET("`express_fee` = #{expressFee,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getOriginPrice() != null) {
            sql.SET("`origin_price` = #{originPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.SET("`point` = #{point,jdbcType=BIGINT}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{status,jdbcType=INTEGER}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_order
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, OrderPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}