package cn.edu.xmu.oomall.order.mapper.generator;

import cn.edu.xmu.oomall.order.mapper.generator.po.OrderItemPo;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderItemPoExample.Criteria;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderItemPoExample.Criterion;
import cn.edu.xmu.oomall.order.mapper.generator.po.OrderItemPoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OrderItemPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String deleteByExample(OrderItemPoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("order_item");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String insertSelective(OrderItemPo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_item");
        
        if (row.getOrderId() != null) {
            sql.VALUES("`order_id`", "#{orderId,jdbcType=BIGINT}");
        }
        
        if (row.getOnsaleId() != null) {
            sql.VALUES("`onsale_id`", "#{onsaleId,jdbcType=BIGINT}");
        }
        
        if (row.getQuantity() != null) {
            sql.VALUES("`quantity`", "#{quantity,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.VALUES("`price`", "#{price,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.VALUES("`discount_price`", "#{discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.VALUES("`point`", "#{point,jdbcType=BIGINT}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("`name`", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getActivityId() != null) {
            sql.VALUES("`activity_id`", "#{activityId,jdbcType=BIGINT}");
        }
        
        if (row.getCouponId() != null) {
            sql.VALUES("`coupon_id`", "#{couponId,jdbcType=BIGINT}");
        }
        
        if (row.getCommented() != null) {
            sql.VALUES("`commented`", "#{commented,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String selectByExample(OrderItemPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`order_id`");
        sql.SELECT("`onsale_id`");
        sql.SELECT("`quantity`");
        sql.SELECT("`price`");
        sql.SELECT("`discount_price`");
        sql.SELECT("`point`");
        sql.SELECT("`name`");
        sql.SELECT("`activity_id`");
        sql.SELECT("`coupon_id`");
        sql.SELECT("`commented`");
        sql.SELECT("`creator_id`");
        sql.SELECT("`creator_name`");
        sql.SELECT("`modifier_id`");
        sql.SELECT("`modifier_name`");
        sql.SELECT("`gmt_create`");
        sql.SELECT("`gmt_modified`");
        sql.FROM("order_item");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrderItemPo row = (OrderItemPo) parameter.get("row");
        OrderItemPoExample example = (OrderItemPoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        if (row.getId() != null) {
            sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getOrderId() != null) {
            sql.SET("`order_id` = #{row.orderId,jdbcType=BIGINT}");
        }
        
        if (row.getOnsaleId() != null) {
            sql.SET("`onsale_id` = #{row.onsaleId,jdbcType=BIGINT}");
        }
        
        if (row.getQuantity() != null) {
            sql.SET("`quantity` = #{row.quantity,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.SET("`price` = #{row.price,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{row.discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.SET("`point` = #{row.point,jdbcType=BIGINT}");
        }
        
        if (row.getName() != null) {
            sql.SET("`name` = #{row.name,jdbcType=VARCHAR}");
        }
        
        if (row.getActivityId() != null) {
            sql.SET("`activity_id` = #{row.activityId,jdbcType=BIGINT}");
        }
        
        if (row.getCouponId() != null) {
            sql.SET("`coupon_id` = #{row.couponId,jdbcType=BIGINT}");
        }
        
        if (row.getCommented() != null) {
            sql.SET("`commented` = #{row.commented,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        sql.SET("`order_id` = #{row.orderId,jdbcType=BIGINT}");
        sql.SET("`onsale_id` = #{row.onsaleId,jdbcType=BIGINT}");
        sql.SET("`quantity` = #{row.quantity,jdbcType=INTEGER}");
        sql.SET("`price` = #{row.price,jdbcType=BIGINT}");
        sql.SET("`discount_price` = #{row.discountPrice,jdbcType=BIGINT}");
        sql.SET("`point` = #{row.point,jdbcType=BIGINT}");
        sql.SET("`name` = #{row.name,jdbcType=VARCHAR}");
        sql.SET("`activity_id` = #{row.activityId,jdbcType=BIGINT}");
        sql.SET("`coupon_id` = #{row.couponId,jdbcType=BIGINT}");
        sql.SET("`commented` = #{row.commented,jdbcType=TINYINT}");
        sql.SET("`creator_id` = #{row.creatorId,jdbcType=BIGINT}");
        sql.SET("`creator_name` = #{row.creatorName,jdbcType=VARCHAR}");
        sql.SET("`modifier_id` = #{row.modifierId,jdbcType=BIGINT}");
        sql.SET("`modifier_name` = #{row.modifierName,jdbcType=VARCHAR}");
        sql.SET("`gmt_create` = #{row.gmtCreate,jdbcType=TIMESTAMP}");
        sql.SET("`gmt_modified` = #{row.gmtModified,jdbcType=TIMESTAMP}");
        
        OrderItemPoExample example = (OrderItemPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(OrderItemPo row) {
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        if (row.getOrderId() != null) {
            sql.SET("`order_id` = #{orderId,jdbcType=BIGINT}");
        }
        
        if (row.getOnsaleId() != null) {
            sql.SET("`onsale_id` = #{onsaleId,jdbcType=BIGINT}");
        }
        
        if (row.getQuantity() != null) {
            sql.SET("`quantity` = #{quantity,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.SET("`price` = #{price,jdbcType=BIGINT}");
        }
        
        if (row.getDiscountPrice() != null) {
            sql.SET("`discount_price` = #{discountPrice,jdbcType=BIGINT}");
        }
        
        if (row.getPoint() != null) {
            sql.SET("`point` = #{point,jdbcType=BIGINT}");
        }
        
        if (row.getName() != null) {
            sql.SET("`name` = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getActivityId() != null) {
            sql.SET("`activity_id` = #{activityId,jdbcType=BIGINT}");
        }
        
        if (row.getCouponId() != null) {
            sql.SET("`coupon_id` = #{couponId,jdbcType=BIGINT}");
        }
        
        if (row.getCommented() != null) {
            sql.SET("`commented` = #{commented,jdbcType=TINYINT}");
        }
        
        if (row.getCreatorId() != null) {
            sql.SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (row.getCreatorName() != null) {
            sql.SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (row.getModifierId() != null) {
            sql.SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (row.getModifierName() != null) {
            sql.SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (row.getGmtCreate() != null) {
            sql.SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (row.getGmtModified() != null) {
            sql.SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, OrderItemPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}