package cn.edu.xmu.oomall.freight.mapper.generator.po;

import cn.edu.xmu.javaee.core.aop.CopyFrom;
import cn.edu.xmu.oomall.freight.dao.bo.Region;

import java.math.BigDecimal;
@CopyFrom(Region.class)
public class RegionPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.level
     *
     * @mbggenerated
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.area_code
     *
     * @mbggenerated
     */
    private Long areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.zip_code
     *
     * @mbggenerated
     */
    private Integer zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.short_name
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.merger_name
     *
     * @mbggenerated
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.pinyin
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.lng
     *
     * @mbggenerated
     */
    private BigDecimal lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.lat
     *
     * @mbggenerated
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_region.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.id
     *
     * @return the value of freight_region.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.id
     *
     * @param id the value for freight_region.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.pid
     *
     * @return the value of freight_region.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.pid
     *
     * @param pid the value for freight_region.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.level
     *
     * @return the value of freight_region.level
     *
     * @mbggenerated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.level
     *
     * @param level the value for freight_region.level
     *
     * @mbggenerated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.area_code
     *
     * @return the value of freight_region.area_code
     *
     * @mbggenerated
     */
    public Long getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.area_code
     *
     * @param areaCode the value for freight_region.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(Long areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.zip_code
     *
     * @return the value of freight_region.zip_code
     *
     * @mbggenerated
     */
    public Integer getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.zip_code
     *
     * @param zipCode the value for freight_region.zip_code
     *
     * @mbggenerated
     */
    public void setZipCode(Integer zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.city_code
     *
     * @return the value of freight_region.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.city_code
     *
     * @param cityCode the value for freight_region.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.name
     *
     * @return the value of freight_region.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.name
     *
     * @param name the value for freight_region.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.short_name
     *
     * @return the value of freight_region.short_name
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.short_name
     *
     * @param shortName the value for freight_region.short_name
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.merger_name
     *
     * @return the value of freight_region.merger_name
     *
     * @mbggenerated
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.merger_name
     *
     * @param mergerName the value for freight_region.merger_name
     *
     * @mbggenerated
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.pinyin
     *
     * @return the value of freight_region.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.pinyin
     *
     * @param pinyin the value for freight_region.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.lng
     *
     * @return the value of freight_region.lng
     *
     * @mbggenerated
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.lng
     *
     * @param lng the value for freight_region.lng
     *
     * @mbggenerated
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.lat
     *
     * @return the value of freight_region.lat
     *
     * @mbggenerated
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.lat
     *
     * @param lat the value for freight_region.lat
     *
     * @mbggenerated
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_region.status
     *
     * @return the value of freight_region.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_region.status
     *
     * @param status the value for freight_region.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}