package cn.edu.xmu.oomall.freight.mapper.generator.po;

import cn.edu.xmu.javaee.core.aop.CopyFrom;
import cn.edu.xmu.oomall.freight.dao.bo.WarehouseRegion;

import java.time.LocalDateTime;
import java.util.Date;
@CopyFrom(WarehouseRegion.class)
public class WarehouseRegionPo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.warehouse_id
     *
     * @mbggenerated
     */
    private Long warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.region_id
     *
     * @mbggenerated
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.begin_time
     *
     * @mbggenerated
     */
    private LocalDateTime beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.end_time
     *
     * @mbggenerated
     */
    private LocalDateTime endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.creator_id
     *
     * @mbggenerated
     */
    private Long creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.creator_name
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.modifier_id
     *
     * @mbggenerated
     */
    private Long modifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.modifier_name
     *
     * @mbggenerated
     */
    private String modifierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.gmt_create
     *
     * @mbggenerated
     */
    private LocalDateTime gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freight_warehouse_region.gmt_modified
     *
     * @mbggenerated
     */
    private LocalDateTime gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.id
     *
     * @return the value of freight_warehouse_region.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.id
     *
     * @param id the value for freight_warehouse_region.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.warehouse_id
     *
     * @return the value of freight_warehouse_region.warehouse_id
     *
     * @mbggenerated
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.warehouse_id
     *
     * @param warehouseId the value for freight_warehouse_region.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.region_id
     *
     * @return the value of freight_warehouse_region.region_id
     *
     * @mbggenerated
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.region_id
     *
     * @param regionId the value for freight_warehouse_region.region_id
     *
     * @mbggenerated
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.begin_time
     *
     * @return the value of freight_warehouse_region.begin_time
     *
     * @mbggenerated
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.begin_time
     *
     * @param beginTime the value for freight_warehouse_region.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.end_time
     *
     * @return the value of freight_warehouse_region.end_time
     *
     * @mbggenerated
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.end_time
     *
     * @param endTime the value for freight_warehouse_region.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.creator_id
     *
     * @return the value of freight_warehouse_region.creator_id
     *
     * @mbggenerated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.creator_id
     *
     * @param creatorId the value for freight_warehouse_region.creator_id
     *
     * @mbggenerated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.creator_name
     *
     * @return the value of freight_warehouse_region.creator_name
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.creator_name
     *
     * @param creatorName the value for freight_warehouse_region.creator_name
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.modifier_id
     *
     * @return the value of freight_warehouse_region.modifier_id
     *
     * @mbggenerated
     */
    public Long getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.modifier_id
     *
     * @param modifierId the value for freight_warehouse_region.modifier_id
     *
     * @mbggenerated
     */
    public void setModifierId(Long modifierId) {
        this.modifierId = modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.modifier_name
     *
     * @return the value of freight_warehouse_region.modifier_name
     *
     * @mbggenerated
     */
    public String getModifierName() {
        return modifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.modifier_name
     *
     * @param modifierName the value for freight_warehouse_region.modifier_name
     *
     * @mbggenerated
     */
    public void setModifierName(String modifierName) {
        this.modifierName = modifierName == null ? null : modifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.gmt_create
     *
     * @return the value of freight_warehouse_region.gmt_create
     *
     * @mbggenerated
     */
    public LocalDateTime getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.gmt_create
     *
     * @param gmtCreate the value for freight_warehouse_region.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freight_warehouse_region.gmt_modified
     *
     * @return the value of freight_warehouse_region.gmt_modified
     *
     * @mbggenerated
     */
    public LocalDateTime getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freight_warehouse_region.gmt_modified
     *
     * @param gmtModified the value for freight_warehouse_region.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
    }
}