package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample.Criteria;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ExpressPoExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class ExpressPoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    public String insertSelective(ExpressPo record) {
        BEGIN();
        INSERT_INTO("freight_express");
        
        if (record.getBillCode() != null) {
            VALUES("`bill_code`", "#{billCode,jdbcType=VARCHAR}");
        }
        
        if (record.getShopLogisticsId() != null) {
            VALUES("`shop_logistics_id`", "#{shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderRegionId() != null) {
            VALUES("`sender_region_id`", "#{senderRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderAddress() != null) {
            VALUES("`sender_address`", "#{senderAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryRegionId() != null) {
            VALUES("`delivery_region_id`", "#{deliveryRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getDeliverAddress() != null) {
            VALUES("`deliver_address`", "#{deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderName() != null) {
            VALUES("`sender_name`", "#{senderName,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderMobile() != null) {
            VALUES("`sender_mobile`", "#{senderMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryName() != null) {
            VALUES("`delivery_name`", "#{deliveryName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("`status`", "#{status,jdbcType=TINYINT}");
        }
        
        if (record.getShopId() != null) {
            VALUES("`shop_id`", "#{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorId() != null) {
            VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    public String selectByExample(ExpressPoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("`id`");
        } else {
            SELECT("`id`");
        }
        SELECT("`bill_code`");
        SELECT("`shop_logistics_id`");
        SELECT("`sender_region_id`");
        SELECT("`sender_address`");
        SELECT("`delivery_region_id`");
        SELECT("`deliver_address`");
        SELECT("`sender_name`");
        SELECT("`sender_mobile`");
        SELECT("`delivery_name`");
        SELECT("`status`");
        SELECT("`shop_id`");
        SELECT("`creator_id`");
        SELECT("`creator_name`");
        SELECT("`modifier_id`");
        SELECT("`modifier_name`");
        SELECT("`gmt_create`");
        SELECT("`gmt_modified`");
        FROM("freight_express");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ExpressPo record = (ExpressPo) parameter.get("record");
        ExpressPoExample example = (ExpressPoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("freight_express");
        
        if (record.getId() != null) {
            SET("`id` = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getBillCode() != null) {
            SET("`bill_code` = #{record.billCode,jdbcType=VARCHAR}");
        }
        
        if (record.getShopLogisticsId() != null) {
            SET("`shop_logistics_id` = #{record.shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderRegionId() != null) {
            SET("`sender_region_id` = #{record.senderRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderAddress() != null) {
            SET("`sender_address` = #{record.senderAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryRegionId() != null) {
            SET("`delivery_region_id` = #{record.deliveryRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getDeliverAddress() != null) {
            SET("`deliver_address` = #{record.deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderName() != null) {
            SET("`sender_name` = #{record.senderName,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderMobile() != null) {
            SET("`sender_mobile` = #{record.senderMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryName() != null) {
            SET("`delivery_name` = #{record.deliveryName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("`status` = #{record.status,jdbcType=TINYINT}");
        }
        
        if (record.getShopId() != null) {
            SET("`shop_id` = #{record.shopId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorId() != null) {
            SET("`creator_id` = #{record.creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            SET("`creator_name` = #{record.creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            SET("`modifier_id` = #{record.modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            SET("`modifier_name` = #{record.modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("`gmt_create` = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("`gmt_modified` = #{record.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("freight_express");
        
        SET("`id` = #{record.id,jdbcType=BIGINT}");
        SET("`bill_code` = #{record.billCode,jdbcType=VARCHAR}");
        SET("`shop_logistics_id` = #{record.shopLogisticsId,jdbcType=BIGINT}");
        SET("`sender_region_id` = #{record.senderRegionId,jdbcType=BIGINT}");
        SET("`sender_address` = #{record.senderAddress,jdbcType=VARCHAR}");
        SET("`delivery_region_id` = #{record.deliveryRegionId,jdbcType=BIGINT}");
        SET("`deliver_address` = #{record.deliverAddress,jdbcType=VARCHAR}");
        SET("`sender_name` = #{record.senderName,jdbcType=VARCHAR}");
        SET("`sender_mobile` = #{record.senderMobile,jdbcType=VARCHAR}");
        SET("`delivery_name` = #{record.deliveryName,jdbcType=VARCHAR}");
        SET("`status` = #{record.status,jdbcType=TINYINT}");
        SET("`shop_id` = #{record.shopId,jdbcType=BIGINT}");
        SET("`creator_id` = #{record.creatorId,jdbcType=BIGINT}");
        SET("`creator_name` = #{record.creatorName,jdbcType=VARCHAR}");
        SET("`modifier_id` = #{record.modifierId,jdbcType=BIGINT}");
        SET("`modifier_name` = #{record.modifierName,jdbcType=VARCHAR}");
        SET("`gmt_create` = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        SET("`gmt_modified` = #{record.gmtModified,jdbcType=TIMESTAMP}");
        
        ExpressPoExample example = (ExpressPoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(ExpressPo record) {
        BEGIN();
        UPDATE("freight_express");
        
        if (record.getBillCode() != null) {
            SET("`bill_code` = #{billCode,jdbcType=VARCHAR}");
        }
        
        if (record.getShopLogisticsId() != null) {
            SET("`shop_logistics_id` = #{shopLogisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderRegionId() != null) {
            SET("`sender_region_id` = #{senderRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getSenderAddress() != null) {
            SET("`sender_address` = #{senderAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryRegionId() != null) {
            SET("`delivery_region_id` = #{deliveryRegionId,jdbcType=BIGINT}");
        }
        
        if (record.getDeliverAddress() != null) {
            SET("`deliver_address` = #{deliverAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderName() != null) {
            SET("`sender_name` = #{senderName,jdbcType=VARCHAR}");
        }
        
        if (record.getSenderMobile() != null) {
            SET("`sender_mobile` = #{senderMobile,jdbcType=VARCHAR}");
        }
        
        if (record.getDeliveryName() != null) {
            SET("`delivery_name` = #{deliveryName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("`status` = #{status,jdbcType=TINYINT}");
        }
        
        if (record.getShopId() != null) {
            SET("`shop_id` = #{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorId() != null) {
            SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_express
     *
     * @mbggenerated
     */
    protected void applyWhere(ExpressPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}