package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.RegionPoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface RegionPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @Delete({
        "delete from freight_region",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @Insert({
        "insert into freight_region (`pid`, `level`, ",
        "`area_code`, `zip_code`, ",
        "`city_code`, `name`, `short_name`, ",
        "`merger_name`, `pinyin`, ",
        "`lng`, `lat`, `status`)",
        "values (#{pid,jdbcType=INTEGER}, #{level,jdbcType=TINYINT}, ",
        "#{areaCode,jdbcType=BIGINT}, #{zipCode,jdbcType=INTEGER}, ",
        "#{cityCode,jdbcType=CHAR}, #{name,jdbcType=VARCHAR}, #{shortName,jdbcType=VARCHAR}, ",
        "#{mergerName,jdbcType=VARCHAR}, #{pinyin,jdbcType=VARCHAR}, ",
        "#{lng,jdbcType=DECIMAL}, #{lat,jdbcType=DECIMAL}, #{status,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @InsertProvider(type=RegionPoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @SelectProvider(type=RegionPoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.TINYINT),
        @Result(column="area_code", property="areaCode", jdbcType=JdbcType.BIGINT),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.INTEGER),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_name", property="shortName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merger_name", property="mergerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="pinyin", property="pinyin", jdbcType=JdbcType.VARCHAR),
        @Result(column="lng", property="lng", jdbcType=JdbcType.DECIMAL),
        @Result(column="lat", property="lat", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT)
    })
    List<RegionPo> selectByExample(RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `pid`, `level`, `area_code`, `zip_code`, `city_code`, `name`, `short_name`, ",
        "`merger_name`, `pinyin`, `lng`, `lat`, `status`",
        "from freight_region",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.TINYINT),
        @Result(column="area_code", property="areaCode", jdbcType=JdbcType.BIGINT),
        @Result(column="zip_code", property="zipCode", jdbcType=JdbcType.INTEGER),
        @Result(column="city_code", property="cityCode", jdbcType=JdbcType.CHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="short_name", property="shortName", jdbcType=JdbcType.VARCHAR),
        @Result(column="merger_name", property="mergerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="pinyin", property="pinyin", jdbcType=JdbcType.VARCHAR),
        @Result(column="lng", property="lng", jdbcType=JdbcType.DECIMAL),
        @Result(column="lat", property="lat", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT)
    })
    RegionPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RegionPo record, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RegionPo record, @Param("example") RegionPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @UpdateProvider(type=RegionPoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RegionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_region
     *
     * @mbggenerated
     */
    @Update({
        "update freight_region",
        "set `pid` = #{pid,jdbcType=INTEGER},",
          "`level` = #{level,jdbcType=TINYINT},",
          "`area_code` = #{areaCode,jdbcType=BIGINT},",
          "`zip_code` = #{zipCode,jdbcType=INTEGER},",
          "`city_code` = #{cityCode,jdbcType=CHAR},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "`short_name` = #{shortName,jdbcType=VARCHAR},",
          "`merger_name` = #{mergerName,jdbcType=VARCHAR},",
          "`pinyin` = #{pinyin,jdbcType=VARCHAR},",
          "`lng` = #{lng,jdbcType=DECIMAL},",
          "`lat` = #{lat,jdbcType=DECIMAL},",
          "`status` = #{status,jdbcType=TINYINT}",
        "where `id` = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RegionPo record);
}