package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.ShopLogisticsPo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ShopLogisticsPoExample;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ShopLogisticsPoExample.Criteria;
import cn.edu.xmu.oomall.freight.mapper.generator.po.ShopLogisticsPoExample.Criterion;

import java.util.List;
import java.util.Map;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class ShopLogisticsPoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    public String insertSelective(ShopLogisticsPo record) {
        BEGIN();
        INSERT_INTO("freight_shop_logistics");
        
        if (record.getShopId() != null) {
            VALUES("`shop_id`", "#{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getLogisticsId() != null) {
            VALUES("`logistics_id`", "#{logisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSecret() != null) {
            VALUES("`secret`", "#{secret,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatorId() != null) {
            VALUES("`creator_id`", "#{creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            VALUES("`creator_name`", "#{creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            VALUES("`modifier_id`", "#{modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            VALUES("`modifier_name`", "#{modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            VALUES("`gmt_create`", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            VALUES("`gmt_modified`", "#{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInvalid() != null) {
            VALUES("`invalid`", "#{invalid,jdbcType=TINYINT}");
        }
        
        if (record.getPriority() != null) {
            VALUES("`priority`", "#{priority,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    public String selectByExample(ShopLogisticsPoExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("`id`");
        } else {
            SELECT("`id`");
        }
        SELECT("`shop_id`");
        SELECT("`logistics_id`");
        SELECT("`secret`");
        SELECT("`creator_id`");
        SELECT("`creator_name`");
        SELECT("`modifier_id`");
        SELECT("`modifier_name`");
        SELECT("`gmt_create`");
        SELECT("`gmt_modified`");
        SELECT("`invalid`");
        SELECT("`priority`");
        FROM("freight_shop_logistics");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ShopLogisticsPo record = (ShopLogisticsPo) parameter.get("record");
        ShopLogisticsPoExample example = (ShopLogisticsPoExample) parameter.get("example");
        
        BEGIN();
        UPDATE("freight_shop_logistics");
        
        if (record.getId() != null) {
            SET("`id` = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getShopId() != null) {
            SET("`shop_id` = #{record.shopId,jdbcType=BIGINT}");
        }
        
        if (record.getLogisticsId() != null) {
            SET("`logistics_id` = #{record.logisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSecret() != null) {
            SET("`secret` = #{record.secret,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatorId() != null) {
            SET("`creator_id` = #{record.creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            SET("`creator_name` = #{record.creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            SET("`modifier_id` = #{record.modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            SET("`modifier_name` = #{record.modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("`gmt_create` = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("`gmt_modified` = #{record.gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInvalid() != null) {
            SET("`invalid` = #{record.invalid,jdbcType=TINYINT}");
        }
        
        if (record.getPriority() != null) {
            SET("`priority` = #{record.priority,jdbcType=INTEGER}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("freight_shop_logistics");
        
        SET("`id` = #{record.id,jdbcType=BIGINT}");
        SET("`shop_id` = #{record.shopId,jdbcType=BIGINT}");
        SET("`logistics_id` = #{record.logisticsId,jdbcType=BIGINT}");
        SET("`secret` = #{record.secret,jdbcType=VARCHAR}");
        SET("`creator_id` = #{record.creatorId,jdbcType=BIGINT}");
        SET("`creator_name` = #{record.creatorName,jdbcType=VARCHAR}");
        SET("`modifier_id` = #{record.modifierId,jdbcType=BIGINT}");
        SET("`modifier_name` = #{record.modifierName,jdbcType=VARCHAR}");
        SET("`gmt_create` = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        SET("`gmt_modified` = #{record.gmtModified,jdbcType=TIMESTAMP}");
        SET("`invalid` = #{record.invalid,jdbcType=TINYINT}");
        SET("`priority` = #{record.priority,jdbcType=INTEGER}");
        
        ShopLogisticsPoExample example = (ShopLogisticsPoExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(ShopLogisticsPo record) {
        BEGIN();
        UPDATE("freight_shop_logistics");
        
        if (record.getShopId() != null) {
            SET("`shop_id` = #{shopId,jdbcType=BIGINT}");
        }
        
        if (record.getLogisticsId() != null) {
            SET("`logistics_id` = #{logisticsId,jdbcType=BIGINT}");
        }
        
        if (record.getSecret() != null) {
            SET("`secret` = #{secret,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatorId() != null) {
            SET("`creator_id` = #{creatorId,jdbcType=BIGINT}");
        }
        
        if (record.getCreatorName() != null) {
            SET("`creator_name` = #{creatorName,jdbcType=VARCHAR}");
        }
        
        if (record.getModifierId() != null) {
            SET("`modifier_id` = #{modifierId,jdbcType=BIGINT}");
        }
        
        if (record.getModifierName() != null) {
            SET("`modifier_name` = #{modifierName,jdbcType=VARCHAR}");
        }
        
        if (record.getGmtCreate() != null) {
            SET("`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModified() != null) {
            SET("`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP}");
        }
        
        if (record.getInvalid() != null) {
            SET("`invalid` = #{invalid,jdbcType=TINYINT}");
        }
        
        if (record.getPriority() != null) {
            SET("`priority` = #{priority,jdbcType=INTEGER}");
        }
        
        WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_shop_logistics
     *
     * @mbggenerated
     */
    protected void applyWhere(ShopLogisticsPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}