package cn.edu.xmu.oomall.freight.mapper.generator;

import cn.edu.xmu.oomall.freight.mapper.generator.po.UndeliverablePo;
import cn.edu.xmu.oomall.freight.mapper.generator.po.UndeliverablePoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;
@Mapper
public interface UndeliverablePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @Delete({
        "delete from freight_undeliverable",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @Insert({
        "insert into freight_undeliverable (`region_id`, `begin_time`, ",
        "`end_time`, `creator_id`, ",
        "`creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, ",
        "`gmt_modified`, `shop_logistics_id`)",
        "values (#{regionId,jdbcType=BIGINT}, #{beginTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{creatorId,jdbcType=BIGINT}, ",
        "#{creatorName,jdbcType=VARCHAR}, #{modifierId,jdbcType=BIGINT}, ",
        "#{modifierName,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModified,jdbcType=TIMESTAMP}, #{shopLogisticsId,jdbcType=BIGINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(UndeliverablePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @InsertProvider(type=UndeliverablePoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insertSelective(UndeliverablePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @SelectProvider(type=UndeliverablePoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="region_id", property="regionId", jdbcType=JdbcType.BIGINT),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="shop_logistics_id", property="shopLogisticsId", jdbcType=JdbcType.BIGINT)
    })
    List<UndeliverablePo> selectByExample(UndeliverablePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "`id`, `region_id`, `begin_time`, `end_time`, `creator_id`, `creator_name`, `modifier_id`, ",
        "`modifier_name`, `gmt_create`, `gmt_modified`, `shop_logistics_id`",
        "from freight_undeliverable",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="region_id", property="regionId", jdbcType=JdbcType.BIGINT),
        @Result(column="begin_time", property="beginTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="creator_name", property="creatorName", jdbcType=JdbcType.VARCHAR),
        @Result(column="modifier_id", property="modifierId", jdbcType=JdbcType.BIGINT),
        @Result(column="modifier_name", property="modifierName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gmt_create", property="gmtCreate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="gmt_modified", property="gmtModified", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="shop_logistics_id", property="shopLogisticsId", jdbcType=JdbcType.BIGINT)
    })
    UndeliverablePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UndeliverablePoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UndeliverablePo record, @Param("example") UndeliverablePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UndeliverablePoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UndeliverablePo record, @Param("example") UndeliverablePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UndeliverablePoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UndeliverablePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freight_undeliverable
     *
     * @mbggenerated
     */
    @Update({
        "update freight_undeliverable",
        "set `region_id` = #{regionId,jdbcType=BIGINT},",
          "`begin_time` = #{beginTime,jdbcType=TIMESTAMP},",
          "`end_time` = #{endTime,jdbcType=TIMESTAMP},",
          "`creator_id` = #{creatorId,jdbcType=BIGINT},",
          "`creator_name` = #{creatorName,jdbcType=VARCHAR},",
          "`modifier_id` = #{modifierId,jdbcType=BIGINT},",
          "`modifier_name` = #{modifierName,jdbcType=VARCHAR},",
          "`gmt_create` = #{gmtCreate,jdbcType=TIMESTAMP},",
          "`gmt_modified` = #{gmtModified,jdbcType=TIMESTAMP},",
          "`shop_logistics_id` = #{shopLogisticsId,jdbcType=BIGINT}",
        "where `id` = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UndeliverablePo record);
}